version: "3"
services:
  elasticsearch:
    image: blacktop/elasticsearch:x-pack-7.7.1
    environment:
      - discovery.type=single-node
    ports:
      - "127.0.0.1:9200:9200"

  kibana:
    depends_on:
      - elasticsearch
    image: blacktop/kibana:x-pack-7.7.1
    environment:
      - xpack.reporting.enabled=false
    ports:
      - "127.0.0.1:5601:5601"
    links:
      - elasticsearch

  filebeat:
    depends_on:
      - kibana
    image: blacktop/filebeat:7.7.1
    links:
      - kibana
      - elasticsearch
    volumes:
      - ./pcap:/pcap
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    command: -e
#
#  zeek:
#    depends_on:
#      - filebeat
#    #build: ./elastic
#    image: blacktop/zeek:elastic
#    network_mode: host
#    volumes:
#      - ./zeek/pcap:/pcap
#      - ./zeek/conf/local.zeek:/usr/local/zeek/share/zeek/site/local.zeek
#      - ./zeek/conf/sniffpass.zeek:/usr/local/zeek/share/zeek/myscripts/sniffpass.zeek
#    command: -C -i eth0 local "Site::local_nets += { 168.100.0.1/16 }"
