filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

    #LogsMonitor
# filebeat.autodiscover:
#   providers:
#     - type: docker
#       hints.enabled: true

filebeat.modules:
- module: zeek
  # All logs
  connection:
    enabled: true
    var.paths:
      - /pcap/conn*.log
  dns:
    enabled: true
    var.paths:
      - /pcap/dns*.log
  http:
    enabled: true
    var.paths:
      - /pcap/http*.log
  files:
    enabled: true
    var.paths:
      - /pcap/files*.log
  ssl:
    enabled: true
    var.paths:
      - /pcap/ssl*.log
  notice:
    enabled: true
    var.paths:
      - /pcap/notice*.log
  capture_loss:
    enabled: true
    var.paths:
      - /pcap/capture_loss*.log
  dce_rpc:
    enabled: true
    var.paths:
      - /pcap/dce_rpc*.log
  dhcp:
    enabled: true
    var.paths:
      - /pcap/dhcp*.log
  dnp3:
    enabled: true
    var.paths:
      - /pcap/dnp3*.log
  dpd:
    enabled: true
    var.paths:
      - /pcap/dpd*.log
  files:
    enabled: true
    var.paths:
      - /pcap/files*.log
  ftp:
    enabled: true
    var.paths:
      - /pcap/ftp*.log
  intel:
    enabled: true
    var.paths:
      - /pcap/intel*.log
  irc:
    enabled: true
    var.paths:
      - /pcap/irc*.log
  kerberos:
    enabled: true
    var.paths:
      - /pcap/kerberos*.log
  modbus:
    enabled: true
    var.paths:
      - /pcap/modbus*.log
  mysql:
    enabled: true
    var.paths:
      - /pcap/mysql*.log
  ntlm:
    enabled: true
    var.paths:
      - /pcap/ntlm*.log
  ocsp:
    enabled: true
    var.paths:
      - /pcap/ocsp*.log
  pe:
    enabled: true
    var.paths:
      - /pcap/pe*.log
  radius:
    enabled: true
    var.paths:
      - /pcap/radius*.log
  rdp:
    enabled: true
    var.paths:
      - /pcap/rdp*.log
  sip:
    enabled: true
    var.paths:
      - /pcap/sip*.log
  rfb:
    enabled: true
    var.paths:
      - /pcap/rfb*.log
  smb_cmd:
    enabled: true
    var.paths:
      - /pcap/smb_cmd*.log
  smb_files:
    enabled: true
    var.paths:
      - /pcap/smb_files*.log
  smtp:
    enabled: true
    var.paths:
      - /pcap/smtp*.log
  snmp:
    enabled: true
    var.paths:
      - /pcap/snmp*.log
  socks:
    enabled: true
    var.paths:
      - /pcap/socks*.log
  smb_mapping:
    enabled: true
    var.paths:
      - /pcap/smb_mapping*.log
  ssh:
    enabled: true
    var.paths:
      - /pcap/ssh*.log
  stats:
    enabled: true
    var.paths:
      - /pcap/stats*.log
  syslog:
    enabled: true
    var.paths:
      - /pcap/syslog*.log
  traceroute:
    enabled: true
    var.paths:
      - /pcap/traceroute*.log
  tunnel:
    enabled: true
    var.paths:
      - /pcap/tunnel*.log
  weird:
    enabled: true
    var.paths:
      - /pcap/weird*.log
  x509:
    enabled: true
    var.paths:
      - /pcap/x509*.log
      
processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

setup.kibana:
  host: '${KIBANA_HOST:kibana:5601}'
